### ISSUE TITLE
How to develop CUDA in vim

### ISSUE THREAD

**Issue by fecet** [ggerganov/ggterm#1]
Hello, glad to know that the renowned author of ggml is also a Vimer :smile: But I'm curious about how can you develop cuda with (neo)vim as `clangd` doen't support it very well and https://developer.nvidia.com/nsight-visual-studio-code-edition only avaliable for vscode AFAIK

**Comment by ggerganov** [comment]
I don't write CUDA very often, but when I do I use `printf` to debug
